source 'https://rubygems.org'

ruby "2.4.0"

gem 'linkeddata', '>= 2.2.2'
gem 'json-ld-preloaded'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.11.4'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
