source 'https://rubygems.org'

ruby "2.4.0"

gem 'linkeddata'
gem 'json-ld-preloaded'
gem 'rspec'
gem 'rake', '>= 12.3.3'
gem 'nokogiri', '>= 1.13.9'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
